### ISSUE TITLE
Problem with reference to Route

### ISSUE THREAD

**Issue by 1337erik** [asciisd/zoho-v3#1]
web.php in the vendor package has an error when referencing the ZohoController, fixed by changing

Route::get('oauth2callback', 'ZohoController@oauth2callback');

to

Route::get('oauth2callback', 'Asciisd\Zoho\Http\Controllers\ZohoController@oauth2callback');

**Comment by aemaddin** [comment]
Hello @1337erik,

this issue fixed at the new vesion 1.0.6

thanks for contribution
