### ISSUE TITLE
Please Add

### ISSUE THREAD

**Issue by 1337erik** [asciisd/zoho-v3#10]
I am manually adding a sort_by and sort_direction to the package, its super simple.

Would highly recommend adding this but I dont know how to do a pull request

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/20347157/210028199-81c0da69-9c47-44b9-8e9a-743af949782d.png">

**Comment by aemaddin** [comment]
Hi @1337erik 

Thanks for the contribution. You can make a pull request by following these steps:

1- take a fork from the project on your account
2- clone the project on your local machine
3- make your edits
4- push your edits to the GitHub
5- on your forked version you can make a pull request to the original project

**Comment by 1337erik** [comment]
Hey man hows it going - I have an issue with the ZOHO api integration - I
posted a few times to the Issues board
https://github.com/asciisd/zoho-v3/issues/11

So I have a local appo and a production app now, Zoho only allows creating
1 Self Client and if both try to grant using the Self Client it will
invalidate the other one. That being said it seems like I need to use a
Server Application API form the API console.

It was working for me for like 30-45 minutes, and then it just kept giving
me "invalid token" errors. Is the refresh token process not working for the
v3 package? Do you have any insight into how this can be added or fixed?

**Comment by outfree** [comment]
@1337erik that is another issue #14 please follow that
