### ISSUE TITLE
only one of these can be installed: illuminate/contracts[v8.83.27], laravel/framework[v10.0.0

### ISSUE THREAD

**Issue by tuyutian** [asciisd/zoho-v3#13]
![image](https://user-images.githubusercontent.com/28928344/227497947-7379135f-7fbb-4862-b6ed-f64f0d94badb.png)
laravel 10 or illuminate/contracts only one i can use ，how can i install this plugin

**Comment by aemaddin** [comment]
Yep, it’s not yet supported laravel 10, soon will be updated

**Comment by aemaddin** [comment]
Please use v2.0.0 for laravel 10 support
