### ISSUE TITLE
[Suggestion] Allow other Authentication Flows e.g. RefreshToken Flow

### ISSUE THREAD

**Issue by papoms** [asciisd/zoho-v3#15]
Hey there and thanks a lot for the package!

The underlying php-sdk-2.1 allows for three different [authentication flows](https://github.com/zoho/zohocrm-php-sdk-2.1#configuration):

- grantToken
- refreshToken
- accessToken

I only had access to credentials allowing the refreshToken Flow so i wanted to use that.
How do you feel about making the authentication flow a configuration option in this package?

**Comment by outfree** [comment]
fixed #15

**Comment by outfree** [comment]
@papoms @aemaddin you can close that - thank you
