### ISSUE TITLE
Create tags and asociate to a lead

### ISSUE THREAD

**Issue by wrtisans** [asciisd/zoho-v3#2]
hello, im trying to create a tag and associate it to a lead ¿is there a way to make that with this package or even access the token to make it from api ?

thanks for your help

**Comment by aemaddin** [comment]
Let me check and revert to you at the weekend.

**Comment by 1337erik** [comment]
The best thing to do to understand the structure that zoho is expecting is to import an already existing record in zoho and log or dd() the response.

I've noticed a few things:
- theres a difference in how different api clients expect the structure. My local setup which uses the SelfClient has to send an object up to Zoho with a slightly different structure than my production server which uses the Server-Client
- sometimes pick-list fields ask for a string value, sometimes a Choice() object.. i dont understand why its a trial-and-error thing to figure out which ones do
- same thing for date fields, sometimes it wants a dateTime object and sometimes it wants a string.. it doesnt make sense but whatever
- Sometimes setting relationships between different zoho records asks for a Record() object with the id of the related record AND one other identifier ( which changes depending on the module, so log the imported record to know which one it expects ). And sometimes it asks for just an array ( not a Record() object ) with this exact same info
- doing this process will also let you know the expected structure of tags, you can set the tags of a record usually by passing in the value as "Tag" => Tag([ 'first tag', 'second tag' ])

I dont know how to "append" a tag yet, however I download the full zoho database and then push up updates after performing operations on them in php so in php its very easy to just append a tag value to the array then pass up the full array of tags including the ones that existed prior
