### ISSUE TITLE
Your configuration files are not serializable.

### ISSUE THREAD

**Issue by mrbuku** [asciisd/zoho-v3#3]
I get the following error when I try to run `php artisan config:cache`. Any idea how I can resolve this?

![Error](https://i.imgur.com/XAt7S9A.png)

Thanks for your help

**Comment by aemaddin** [comment]
Hello @mrbuku,

Yes, I think I can help with that, but it needs an update. So keep checking for updates, and I will fix it this weekend.

So you can avoid caching config to prevent this issue until I finish the update.

**Comment by mrbuku** [comment]
@aemaddin Thank you.

**Comment by jayomayan** [comment]
I know this is already reported. Is there a fix for this already?

**Comment by jaketoolson** [comment]
@aemaddin  - This is still a problem.

**Comment by aemaddin** [comment]
Just one more hint to make this issue gone,

you need to update the `config/zoho.php` file with a new one or update line 105 to:

`'environment' => env('ZOHO_SANDBOX', 'false'),`

instead of 

`'environment' => USDataCenter::PRODUCTION(),`
