### ISSUE TITLE
Failed install Laravel 11

### ISSUE THREAD

**Issue by nekithh** [asciisd/zoho-v3#32]
![Знімок екрана 2024-08-01 123047](https://github.com/user-attachments/assets/4b92805f-32ee-4ea0-b5b5-a504fae644f3)
Error when downloading through composer, how to fix it?

**Comment by maxabba** [comment]
Currently, it's not possible to install this library on Laravel 11 because the Contracts used within the library are not supported by Laravel 11.

@asciisd needs to update the library for compatibility with Laravel 11.

On Laravel 10, it is working perfectly.
