### ISSUE TITLE
Getting "invalid_client" error

### ISSUE THREAD

**Issue by BartCardan** [asciisd/zoho-v3#8]
Hello,
I've followed all steps on the readme.
I always get the error "invalid_client".
I am running laravel on localhost.

These is inside my .env file
`
ZOHO_CLIENT_ID="1000.0IOA.........."
ZOHO_CLIENT_SECRET="892598bc9................"
ZOHO_REDIRECT_URI=http://localhost:8000/zoho/oauth2callback
ZOHO_CURRENT_USER_EMAIL="b.......@te........"
ZOHO_TOKEN="1000.e82a5234fda7................."
ZOHO_SANDBOX=true
ZOHO_ACCOUNTS_URL=https://accounts.zoho.eu
ZOHO_API_BASE_URL=www.zohoapis.eu
`

Any idea what is going wrong? I can't figure out what to do next.

**Comment by aemaddin** [comment]
Hello @BartCardan 

can you please check if your config file SANDBOX default value is boolean false not a string "false"

**Comment by aemaddin** [comment]
You can find this on `config/zoho.php:105`

`'environment' => env('ZOHO_SANDBOX', false),`

**Comment by aemaddin** [comment]
also please update to the latest version and you can find a new feature that will set EUDatacenter here

**Comment by BartCardan** [comment]
@aemaddin Thank you. I will check later this week and report back asap. Please leave issue open for couple of days.

**Comment by BartCardan** [comment]
Thank you! I have updated to most recent version. Connection works fine now.
